### ISSUE TITLE
feature: Follow path through multiple steps

### ISSUE THREAD

**Issue by ra100** [maptalks/maptalks.odline#3]
Would it be possible to support multiple points along the path, not just origin-destination, but:
origin->point2->point3->destination?

**Comment by fuzhenn** [comment]
Although OD-Line usually means a simple line of origin-desitination, this is absolutely a good idea worthy for consideration.
It's possible for sure, but I need to find some time to check for potential side effects.

I will come back later.

**Comment by fuzhenn** [comment]
Hey, @ra100 , after some consideration, I think it's better to keep `maptalks.odline` as simple as it is now and not to bring this feature on board.

But this feature is absolutely useful in many cases,  I would like to create a new plugin naming `ParticlePathLayer` (or any better one?) for this.

Any suggestion?

**Comment by ra100** [comment]
@fuzhenn that makes sense, don't overcomplicate simple modules.
And I like `ParticlePathLayer` or `PathFollowLayer`, `TraceLayer`? But it's particleLayer along the path, so the fist one is nice.

**Comment by fuzhenn** [comment]
Great!

I will find some time to implement `ParticlePathLayer`, will keep you posted here.

**Comment by fuzhenn** [comment]
Sorry for the late reply.
You may checkout [maptalks.e3](https://github.com/maptalks/maptalks.e3), it has what you want ([example](https://maptalks.github.io/maptalks.e3/demo/bus.html)), if you don't mind loading another library [echarts](https://github.com/ecomfe/echarts) into you app.

**Comment by ra100** [comment]
That looks awesome, and I don't have problem adding another library to my project. Thanks.

**Comment by ra100** [comment]
I finally got to do something with it :)
![2d648caa-61a1-4c8d-b143-ac5e0bc07307](https://user-images.githubusercontent.com/3185410/34314806-fb28dde2-e777-11e7-9845-382e57386989.png)
